"""
MSS Report
Version : 1.0
Sprint : 35.0
Compatible : v0.31
"""

from dataclasses import dataclass, field

from mss.domain.trade_statistics import TradeStatistics


@dataclass
class Report:

    #
    # Summary
    #
    processed_candles: int = 0

    generated_signals: int = 0

    executed_trades: int = 0

    execution_time: float = 0.0

    #
    # Statistics
    #
    statistics: TradeStatistics = field(

        default_factory=TradeStatistics

    )

    #
    # Titles
    #
    title: str = "MSS BACKTEST REPORT"

    subtitle: str = "Generated by MSS"

    #
    # Sections
    #
    summary_lines: list[str] = field(

        default_factory=list

    )

    performance_lines: list[str] = field(

        default_factory=list

    )

    risk_lines: list[str] = field(

        default_factory=list

    )

    equity_lines: list[str] = field(

        default_factory=list

    )

    #
    # Output
    #
    pdf_file: str = ""

    valid: bool = False