"""
MSS Order Builder
Version : 1.0
Sprint : 9.3
Compatible : v0.20
"""

from mss.domain.trade_order import TradeOrder


class OrderBuilder:

    def build(
        self,
        symbol: str,
        trade_setup,
        risk_profile,
    ) -> TradeOrder:

        order = TradeOrder()

        if trade_setup is None:
            return order

        if risk_profile is None:
            return order

        if not trade_setup.valid:
            return order

        if not risk_profile.valid:
            return order

        order.symbol = symbol

        order.direction = trade_setup.direction

        order.volume = risk_profile.lot_size

        order.entry = trade_setup.entry

        order.stop_loss = trade_setup.stop_loss

        order.take_profit_1 = trade_setup.take_profit_1

        order.take_profit_2 = trade_setup.take_profit_2

        order.risk_percent = risk_profile.risk_percent

        order.rr = trade_setup.rr

        order.comment = "Generated by MSS Engine"

        order.valid = True

        return order